### ISSUE TITLE
Revised article TODO

### ISSUE THREAD

**Issue by maximecb** [mila-iqia/babyai#4]
Here is a list of things to complete for the revised article. Most of these will probably be done in January:

- [x] Investigate one-hot representation of observations, validate performance effect (Maxime)
  - Effect is mixed, not clearly beneficial
- [x] Validate and test new bot (Salem)
- [x] Add bibtex for BabyAI paper to repo
- [X] Deanonymize paper
- [X] Regenerate all demonstrations (depend on new bot)
- [x] Re-run all experiments, retrain all models (Dima)
- [x] Update results in paper
- [x] Update bot diagrams in paper
- [x] Last proofreading pass on revised paper
- [x] Update paper on OpenReview/arXiv
- [x] Repackage and reupload new demos on website
- [x] Regenerate Docker container with new trained models
- [ ] Document commands used to train big & small models in [iclr19 branch README](https://github.com/mila-iqia/babyai/blob/iclr19/README.md)

Camera-ready deadline is February 22nd.

**Comment by maximecb** [comment]
@rizar Since we're not as pressed for time, I think it would be nice to include more results in Table 4. For instance, I'm curious how much harder GoToObjMaze is than GoToObj.

**Comment by maximecb** [comment]
We still need to document the commands used to train big and small models in the ICLR19 branch readme.

**Comment by rizar** [comment]
I have a lot of good stuff in my development branch that I want now to merge to ICLR19 branch, including the info on how to train models. There will be a PR (or a few of them) this week.
